FROM node:16

WORKDIR /app

ARG ARG_USERNAME
ARG ARG_PASSWORD
ARG ARG_CLUSTER
ARG ARG_DATABASE
ARG ARG_MQTT_URL
ARG ARG_API_URL

ENV DB_USERNAME=${ARG_USERNAME}
ENV DB_PASSWORD=${ARG_PASSWORD}
ENV DB_CLUSTER=${ARG_CLUSTER}
ENV DB_DATABASE=${ARG_DATABASE}
ENV NEXT_PUBLIC_API_URL=${ARG_API_URL}

RUN echo "$DB_USERNAME"
RUN echo "$DB_PASSWORD"
RUN echo "$DB_CLUSTER"
RUN echo "$DB_DATABASE"
RUN echo "$NEXT_PUBLIC_API_URL"

COPY . ./
RUN yarn install --pure-lockfile && yarn build

EXPOSE 3000

CMD ["yarn", "start"]
