name: Build & Deploy
on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "ARG_USERNAME=${{secrets.DB_USERNAME}}"
            "ARG_PASSWORD=${{secrets.DB_PASSWORD}}"
            "ARG_CLUSTER=${{secrets.DB_CLUSTER}}"
            "ARG_DATABASE=${{secrets.DB_DATABASE}}"
            "ARG_API_URL=${{secrets.NEXT_PUBLIC_API_URL}}"
            "ARG_MQTT_URL=${{secrets.MQTT_URL}}"
      - name: Import and start on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: cd control-app && docker compose up -d --pull
