name: Build & Deploy
on:
  push:
    branches:
    - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Build container
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        load: true
        tags: insektionen/control-app:latest
        build-args: |
          ARG_USERNAME = ${{ secrets.ARG_USERNAME }}
          ARG_PASSWORD = ${{ secrets.ARG_PASSWORD }}
          ARG_CLUSTER = ${{ secrets.ARG_CLUSTER }}
          ARG_DATABASE = ${{ secrets.ARG_DATABASE }}
          ARG_MQTT_URL = ${{ secrets.MQTT_URL }}
    - name: Export container
      run: docker save insektionen/control-app:latest | gzip > control-app_latest.tar.gz
    - name: Copy to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        source: "control-app_latest.tar.gz"
        target: "~/"
    - name: Import and start on Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: docker load < control-app_latest.tar.gz && cd control-app && docker-compose up -d